const GET_BANNER  = 'GET_BANNER'
const GET_PRODUCS = 'GET_PRODUCS'
const CHANGE_HEADER = 'CHANGE_HEADER'
const GET_CARTPRODUCT = 'GET_CARTPRODUCT'
export { GET_BANNER , GET_PRODUCS , CHANGE_HEADER ,GET_CARTPRODUCT}